spring:
  application:
    name: table-split
  datasource:
    url: jdbc:h2:mem:table-split
  messages:
    basename: messages
    encoding: UTF-8

cloudinary:
  cloud-name:
  api-key:
  api-secret:
  root-folder: dev

app:
  time:
    zone-id: Europe/Lisbon

logging:
  level:
    ROOT: INFO
    org:
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF
      springframework:
        transaction: OFF
    dev.thiagooliveira: DEBUG