spring:
  application:
    name: table-split-agent
  ai:
    openai:
      chat:
        options:
          model: gpt-4o-mini
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration
  rabbitmq:
    template:
      retry:
        enabled: true
        initial-interval: 5s
        max-retries: 5
    listener:
      simple:
        prefetch: 1

server:
  port: 9000

app:
  configured: false
  manager:
    url: https://www.tablesplit.app
  version: "@project.version@"

logging:
  level:
    dev.thiagooliveira: INFO