spring:
  application:
    name: table-split-agent
  rabbitmq:
    addresses:
    template:
      retry:
        enabled: true
        initial-interval: 5s
        max-attempts: 5

server:
  port: 8081

app:
  version: "@project.version@"

logging:
  level:
    dev.thiagooliveira: INFO