cloudinary:
  root-folder: prod
app:
  register:
    enabled: false
  dashboard:
    executor:
      core-pool-size: 6
      max-pool-size: 12
      queue-capacity: 30
      thread-name-prefix: dashboard-prod-pool-
telegram:
  bot:
    base-url: https://www.tablesplit.app/

logging:
  level:
    ROOT: WARN
    org:
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF
      springframework:
        transaction: OFF
    dev.thiagooliveira: INFO
    liquibase: OFF