cloudinary:
  root-folder: prod
app:
  register:
    enabled: false
telegram:
  bot:
    base-url: https://www.tablesplit.app/

logging:
  level:
    ROOT: WARN
    org:
      hibernate:
        SQL: OFF
        type:
          descriptor:
            sql:
              BasicBinder: OFF
      springframework:
        transaction: OFF
    dev.thiagooliveira: INFO
    liquibase: OFF