springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha
    displayRequestDuration: true
  api-docs:
    enabled: true
    path: /v3/api-docs
  show-actuator: true
