spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tablesplit
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  h2:
    console:
      enabled: false
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
